kind: Service
apiVersion: v1
metadata:
  name: soundstorm
spec:
  selector:
    app: soundstorm
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
