image: alpine/edge
packages:
  - docker
  - py-pip
sources:
  - https://git.sr.ht/~tubbo/soundstorm
tasks:
  - compose: pip install docker-compose --user
  - init: cd soundstorm && ./bin/soundstorm init
  - start: cd soundstorm && ./bin/soundstorm start
  - test: cd soundstorm && ./bin/soundstorm lint test
  - ship: cd soundstorm && ./bin/soundstorm ship
