image: archlinux
packages:
  - docker
  - docker-compose
sources:
  - https://git.sr.ht/~tubbo/soundstorm
tasks:
  - init: cd soundstorm && ./bin/soundstorm init
  - start: cd soundstorm && ./bin/soundstorm start
  - test: cd soundstorm && ./bin/soundstorm lint test
