image: alpine/edge
packages:
  - ruby
  - nodejs
  - postgresql
sources:
  - https://git.sr.ht/~tubbo/soundstorm
tasks:
  - setup: 'cd soundstorm && sudo ./bin/setup'
  - test: 'cd soundstorm && ./bin/rails test'
