image: archlinux
packages:
  - docker
  - docker-compose
sources:
  - https://git.sr.ht/~tubbo/soundstorm
tasks:
  - start: systemd start docker
  - init: |
      cd soundstorm
      ./bin/soundstorm init
  - test: |
      cd soundstorm
      ./bin/soundstorm lint test
  - release: |
      cd soundstorm
      git describe --exact-match HEAD
      [ $? == 0 ] && ./bin/soundstorm release
