image: alpine/edge
packages:
  - ruby
  - ruby-dev
  - nodejs
  - postgresql
  - postgresql-dev
  - zlib
  - zlib-dev
sources:
  - https://git.sr.ht/~tubbo/soundstorm
tasks:
  - install: cd soundstorm && sudo ./bin/setup
  - test: cd soundstorm && ./bin/rails test
