image: alpine/edge
packages:
  - docker
  - py-pip
sources:
  - https://git.sr.ht/~tubbo/soundstorm
tasks:
  - compose: pip install docker-compose --user
  - enter: cd soundstorm
  - init: ./bin/soundstorm init
  - start: ./bin/soundstorm start
  - test: ./bin/soundstorm lint test
