version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - soundstorm
  web:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
      - redis
    links:
      - mailcatcher
    volumes:
      - .:/srv
      - node_modules:/node_modules
      - yarn_cache:/root/.yarn-cache
      - bundle:/gems
    environment:
      - DOCKER=1
      - SOUNDSTORM_ADMIN_USERNAME
      - SOUNDSTORM_ADMIN_EMAIL
      - SOUNDSTORM_ADMIN_PASSWORD
    networks:
      - soundstorm
  mailcatcher:
    image: mailcatcher
    ports:
      - '1080:1080'
volumes:
  postgresql:
  bundle:
  node_modules:
  yarn_cache:
networks:
  soundstorm:
