#
# Base services configuration for Soundstorm. This describes the bare
# minimum containers that are used to construct any Soundstorm
# environment.
#

version: '3'
services:
  # PostgreSQL is the primary persistent data store for the application.
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data

  # Elasticsearch provides a search index for all models.
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3

  # The "majestic monolith" that powers Soundstorm, a Rails application
  # serving HTML (for the most part) and containing all of the logic
  # needed to run a Soundstorm instance.
  web:
    command: bin/rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db
      - search
    volumes:
      - yarn_cache:/root/.yarn
    environment:
      - BUNDLE_APP_CONFIG=/srv/.bundle
      - DATABASE_URL=postgres://postgres@db:5432
      - ELASTICSEARCH_URL=http://search:9200
      - SOUNDSTORM_HOST

volumes:
  postgresql:
  yarn_cache:
