#
# Services configuration for Soundstorm
#

version: '3'
services:
  # PostgreSQL is the primary persistent data store for the application.
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - soundstorm

  # Redis is used in production to store the background job queue and
  # the various cached HTML and data used throughout the application.
  # redis:
  #   image: redis

  # In development, Mailcatcher is used to receive and process emails.
  # It can be accessed at http://localhost:1080.
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'

  # The "majestic monolith" that powers Soundstorm, a Rails application
  # serving HTML (for the most part) and containing all of the logic
  # needed to run a Soundstorm instance.
  web: &rails
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
      # - redis
    links:
      - mailcatcher
    volumes:
      - .:/srv
      - node_modules:/node_modules
      - yarn_cache:/root/.yarn-cache
      - bundle:/gems
    environment:
      - DOCKER=true
      - SOUNDSTORM_ADMIN_USERNAME
      - SOUNDSTORM_ADMIN_EMAIL
      - SOUNDSTORM_ADMIN_PASSWORD
    networks:
      - soundstorm

  # Background job processor for the application
  # sidekiq:
  #   <<: *rails
  #   command: bin/bundle exec sidekiq -C config/sidekiq.yml

volumes:
  postgresql:
  bundle:
  node_modules:
  yarn_cache:
networks:
  soundstorm:
