#
# Development services configuration. Installs various external services
# used to aid developers and sets up build caches for application
# dependencies.
#
version: '3'
services:
  # In development, Mailcatcher is used to receive and process emails.
  # It can be accessed at http://localhost:1080.
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'

  # Expose Elasticsearch port 9200 to all users in development for
  # debugging purposes.
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=soundstorm
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1G


  # Cache application dependencies and use the local database in
  # development
  web:
    build: .
    ports:
      - "${RAILS_PORT}:3000"
    links:
      - mailcatcher
    depends_on:
      - search
    volumes:
      - .:/srv
      - node_modules:/node_modules
      - bundle:/gems
    environment:
      - YARN_MODULE_PATH=/node_modules
    entrypoint: ./bin/entrypoint.sh

volumes:
  bundle:
  node_modules:
  elasticsearch:
