version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    command: bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/srv
      - node_modules:/node_modules
      - yarn_cache:/root/.yarn-cache
      - bundle:/gems
    environment:
      - DOCKER=1
      - SOUNDSTORM_ADMIN_USERNAME
      - SOUNDSTORM_ADMIN_EMAIL
      - SOUNDSTORM_ADMIN_PASSWORD
volumes:
  postgresql:
  bundle:
  node_modules:
  yarn_cache:
